# Generated by Django 3.2.9 on 2022-07-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
