# Generated by Django 3.2.9 on 2022-07-23 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0002_alter_comment_com_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Ad.notice'),
        ),
    ]
