# Generated by Django 3.2.9 on 2022-07-26 16:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0003_alter_comment_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
