# Generated by Django 3.2.9 on 2022-07-26 16:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0004_alter_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
