# Generated by Django 3.2.9 on 2022-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0005_alter_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Видимость комментария'),
        ),
    ]
