# Generated by Django 3.2.9 on 2022-07-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0008_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('TK', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('SL', 'Торговцы'), ('GM', 'Гилдмастеры'), ('KG', 'Квестгиверы'), ('KZ', 'Кузнецы'), ('TN', 'Кожевники'), ('ZV', 'Зельевары'), ('SP', 'Мастера заклинаний')], max_length=2),
        ),
    ]
